[package]
name = "paint"
version = "0.1.0"
authors = ["planet0104 <planet0104@gmail.com>"]

[dependencies]
jni = "0.10.1"
lodepng = "2.1.5"
#iui = "0.3"
#ui-sys = "0.1.3"
#bitflags = "1.0.3"
rand = "0.5.3"
winit = "0.16.0"

piston = "0.37.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"
piston_window = "*"



[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.1.2"

[lib]
name = "paint"
crate-type=["dylib"]